#!/bin/bash

# source style checker
source .git/hooks/style

# init
have_violation=0

echo "checking for style guide violations"


# get list of files staged
files=$(git diff --cached --name-only)

# iterate through files
for file in ${files}
do
	# check style guide
	if ! check_style_guide ${file} "cat ${file}"
	then
		have_violation=1
	fi
done

exit ${have_violation}
