#!/bin/bash

# grep regex patterns, checking for style guide violations
regex=(
	# trailing whitespace
	" -e '\s+$'"
	
	# pointer: type* id
	" -e '\w\*+\s+'"

	# pointer: type ( *fct_p)
	" -e '\(\s+\*'"
)


# \brief	check style guide for following file types:
#				h, c, cc, cpp, cxx, l, lex, y, yacc, gperf
#
# \param	$1	file name
# \param	$2	command how to acquire the file content
# \param	$3	optional, file for grep output redirection
#
# \return	0	no violations detected
#			1	violations detected
function check_style_guide(){
	local file=$1
	local content=$2
	local log=""

	# check file type
	local suffix=$(echo ${file} | rev | cut -d '.' -f 1 | rev)
	
	if [ "${suffix}" != "h" \
	  -a "${suffix}" != "c" \
	  -a "${suffix}" != "cc" \
	  -a "${suffix}" != "cpp" \
	  -a "${suffix}" != "cxx" \
	  -a "${suffix}" != "l" \
	  -a "${suffix}" != "lex" \
	  -a "${suffix}" != "y" \
	  -a "${suffix}" != "yacc" \
	  -a "${suffix}" != "gperf" \
	  ];then
	  	return 0
	fi

	# check for output redirection
	if [ "$3" != "" ];then
		local log=" > $3"
	fi

	# issue grep
	eval ${content} "|" \
		 "GREP_COLOR='2;30;41' grep -nHE --color --label="${file} \
		 ${regex[*]} \
		 ${log}

	# check result
	if [ $? == 0 ];then
		return 1
	fi

	return 0
}
